package com.oliviaborath.movierecommendationapi.config;

import com.oliviaborath.movierecommendationapi.models.Movie;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Arrays;
import java.util.List;

@Configuration
public class MovieConfiguration {

    @Bean
    public List<Movie> movies() {
        return Arrays.asList(
            new Movie("The Shawshank Redemption", Arrays.asList("Drama"), "movie"),
            new Movie("The Godfather", Arrays.asList("Crime", "Drama"), "movie"),
            new Movie("Schindler's List", Arrays.asList("Biography", "Drama", "History"), "movie"),
            new Movie("12 Angry Men", Arrays.asList("Crime", "Drama"), "movie"),
            new Movie("The Lord of the Rings: The Return of the King", Arrays.asList("Action", "Adventure", "Drama"), "movie"),
            new Movie("The Godfather Part II", Arrays.asList("Crime", "Drama"), "movie"),
            new Movie("Pulp Fiction", Arrays.asList("Crime", "Drama"), "movie"),
            new Movie("Forrest Gump", Arrays.asList("Drama", "Romance"), "movie"),
            new Movie("The Good, the Bad and the Ugly", Arrays.asList("Adventure", "Western"), "movie"),
            new Movie("Goodfellas", Arrays.asList("Biography", "Crime", "Drama"), "movie"),
            new Movie("One Flew Over the Cuckoo's Nest", Arrays.asList("Drama"), "movie"),
            new Movie("Saving Private Ryan", Arrays.asList("Drama", "War"), "movie"),
            new Movie("The Silence of the Lambs", Arrays.asList("Crime", "Drama", "Thriller"), "movie"),
            new Movie("The Green Mile", Arrays.asList("Crime", "Drama", "Fantasy"), "movie"),
            new Movie("Star Wars: Episode IV - A New Hope", Arrays.asList("Action", "Adventure", "Fantasy"), "movie"),
            new Movie("It's a Wonderful Life", Arrays.asList("Drama", "Family", "Fantasy"), "movie"),
            new Movie("Gladiator", Arrays.asList("Action", "Adventure", "Drama"), "movie"),
            new Movie("The Pianist", Arrays.asList("Biography", "Drama", "Music"), "movie"),
            new Movie("Psycho", Arrays.asList("Horror", "Mystery", "Thriller"), "movie"),
            new Movie("Casablanca", Arrays.asList("Drama", "Romance", "War"), "movie"),
            new Movie("Rear Window", Arrays.asList("Mystery", "Thriller"), "movie"),
            new Movie("City Lights", Arrays.asList("Comedy", "Drama", "Romance"), "movie"),
            new Movie("Raiders of the Lost Ark", Arrays.asList("Action", "Adventure"), "movie"),
            new Movie("Apocalypse Now", Arrays.asList("Drama", "Mystery", "War"), "movie"),
            new Movie("Amadeus", Arrays.asList("Biography", "Drama", "Music"), "movie"),
            new Movie("Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", Arrays.asList("Comedy", "War"), "movie"),
            new Movie("Sunset Blvd.", Arrays.asList("Drama", "Film-Noir"), "movie"),
            new Movie("The Great Dictator", Arrays.asList("Comedy", "Drama", "War"), "movie"),
            new Movie("Braveheart", Arrays.asList("Biography", "Drama", "History"), "movie"),
            new Movie("Good Will Hunting", Arrays.asList("Drama", "Romance"), "movie"),
            new Movie("On the Waterfront", Arrays.asList("Crime", "Drama", "Thriller"), "movie"),
            new Movie("The Bridge on the River Kwai", Arrays.asList("Adventure", "Drama", "War"), "movie"),
            new Movie("It Happened One Night", Arrays.asList("Comedy", "Romance"), "movie"),
            new Movie("The Best Years of Our Lives", Arrays.asList("Drama", "Romance", "War"), "movie"),
            new Movie("All Quiet on the Western Front", Arrays.asList("Drama", "War"), "movie"),
            new Movie("The Grapes of Wrath", Arrays.asList("Drama"), "movie"),
            new Movie("Mr. Smith Goes to Washington", Arrays.asList("Comedy", "Drama"), "movie"),
            new Movie("Rain Man", Arrays.asList("Drama"), "movie"),
            new Movie("Dances with Wolves", Arrays.asList("Adventure", "Drama", "Western"), "movie"),
            new Movie("The Graduate", Arrays.asList("Comedy", "Drama", "Romance"), "movie"),
            new Movie("Butch Cassidy and the Sundance Kid", Arrays.asList("Biography", "Crime", "Drama"), "movie"),
            new Movie("Annie Hall", Arrays.asList("Comedy", "Romance"), "movie"),
            new Movie("High Noon", Arrays.asList("Drama", "Thriller", "Western"), "movie"),
            new Movie("The Maltese Falcon", Arrays.asList("Crime", "Film-Noir", "Mystery"), "movie"),
            new Movie("Titanic", Arrays.asList("Drama", "Romance"), "movie"),
            new Movie("E.T. the Extra-Terrestrial", Arrays.asList("Adventure", "Family", "Sci-Fi"), "movie"),
            new Movie("The Philadelphia Story", Arrays.asList("Comedy", "Romance"), "movie"),
            new Movie("Doctor Zhivago", Arrays.asList("Drama", "Romance", "War"), "movie"),
            new Movie("The Searchers", Arrays.asList("Adventure", "Drama", "Western"), "movie"),
            new Movie("A Streetcar Named Desire", Arrays.asList("Drama"), "movie"),
            new Movie("Patton", Arrays.asList("Biography", "Drama", "War"), "movie"),
            new Movie("Midnight Cowboy", Arrays.asList("Drama"), "movie"),
            new Movie("My Fair Lady", Arrays.asList("Drama", "Family", "Musical"), "movie"),
            new Movie("Stagecoach", Arrays.asList("Adventure", "Drama", "Western"), "movie"),
            new Movie("The French Connection", Arrays.asList("Action", "Crime", "Drama"), "movie"),
            new Movie("Bonnie and Clyde", Arrays.asList("Action", "Biography", "Crime"), "movie"),
            new Movie("The African Queen", Arrays.asList("Adventure", "Drama", "Romance"), "movie"),
            new Movie("A Place in the Sun", Arrays.asList("Drama", "Romance"), "movie"),
            new Movie("Close Encounters of the Third Kind", Arrays.asList("Drama", "Sci-Fi"), "movie"),
            new Movie("West Side Story", Arrays.asList("Crime", "Drama", "Musical"), "movie"),
            new Movie("From Here to Eternity", Arrays.asList("Drama", "Romance", "War"), "movie"),
            new Movie("Rebel Without a Cause", Arrays.asList("Drama"), "movie"),
            new Movie("Giant", Arrays.asList("Drama", "Western"), "movie"),
            new Movie("Shane", Arrays.asList("Drama", "Western"), "movie"),
            new Movie("Nashville", Arrays.asList("Comedy", "Drama", "Music"), "movie"),
            new Movie("Yankee Doodle Dandy", Arrays.asList("Biography", "Drama", "Family"), "movie"),
            new Movie("Mutiny on the Bounty", Arrays.asList("Adventure", "Biography", "Drama"), "movie"),
            new Movie("Wuthering Heights", Arrays.asList("Drama", "Romance"), "movie"),
            new Movie("2001: A Space Odyssey", Arrays.asList("Adventure", "Sci-Fi"), "movie"),
            new Movie("To Kill a Mockingbird", Arrays.asList("Crime", "Drama"), "movie"),
            new Movie("A Clockwork Orange", Arrays.asList("Crime", "Sci-Fi"), "movie"),
            new Movie("Lawrence of Arabia", Arrays.asList("Adventure", "Biography", "Drama"), "movie"),
            new Movie("Vertigo", Arrays.asList("Mystery", "Romance", "Thriller"), "movie"),
            new Movie("Citizen Kane", Arrays.asList("Drama", "Mystery"), "movie"),
            new Movie("Singin' in the Rain", Arrays.asList("Comedy", "Musical", "Romance"), "movie"),
            new Movie("North by Northwest", Arrays.asList("Action", "Adventure", "Mystery"), "movie"),
            new Movie("The Apartment", Arrays.asList("Comedy", "Drama", "Romance"), "movie"),
            new Movie("Double Indemnity", Arrays.asList("Crime", "Drama", "Film-Noir"), "movie"),
            new Movie("Jurassic Park", Arrays.asList("Action", "Adventure", "Sci-Fi"), "movie"),
            new Movie("Taxi Driver", Arrays.asList("Crime", "Drama"), "movie"),
            new Movie("Chinatown", Arrays.asList("Drama", "Mystery", "Thriller"), "movie"),
            new Movie("Gone with the Wind", Arrays.asList("Drama", "Romance", "War"), "movie"),
            new Movie("Unforgiven", Arrays.asList("Drama", "Western"), "movie"),
            new Movie("Some Like It Hot", Arrays.asList("Comedy", "Music", "Romance"), "movie"),
            new Movie("The Treasure of the Sierra Madre", Arrays.asList("Adventure", "Drama", "Western"), "movie"),
            new Movie("The Exorcist", Arrays.asList("Horror"), "movie"),
            new Movie("Jaws", Arrays.asList("Adventure", "Mystery", "Thriller"), "movie"),
            new Movie("Fargo", Arrays.asList("Crime", "Thriller"), "movie"),
            new Movie("Rocky", Arrays.asList("Drama", "Sport"), "movie"),
            new Movie("The Wizard of Oz", Arrays.asList("Adventure", "Family", "Fantasy"), "movie"),
            new Movie("Platoon", Arrays.asList("Drama", "War"), "movie"),
            new Movie("The Deer Hunter", Arrays.asList("Drama", "War"), "movie"),
            new Movie("The Sound of Music", Arrays.asList("Biography", "Drama", "Family"), "movie"),
            new Movie("Raging Bull", Arrays.asList("Biography", "Drama", "Sport"), "movie"),
            new Movie("Network", Arrays.asList("Drama"), "movie"),
            new Movie("Ben-Hur", Arrays.asList("Adventure", "Drama"), "movie"),
            new Movie("The Third Man", Arrays.asList("Film-Noir", "Mystery", "Thriller"), "movie"),

            new Movie("The Brady Bunch", Arrays.asList("Comedy", "Family"), "tv show"),
            new Movie("Modern Family", Arrays.asList("Comedy", "Drama", "Romance"), "tv show"),
            new Movie("Battlestar Galactica", Arrays.asList("Action", "Adventure", "Drama"), "tv show"),
            new Movie("Glee", Arrays.asList("Comedy", "Drama", "Music"), "tv show"),
            new Movie("Married... with Children", Arrays.asList("Comedy"), "tv show"),
            new Movie("Diff'rent Strokes", Arrays.asList("Comedy", "Drama", "Family"), "tv show"),
            new Movie("The A-Team", Arrays.asList("Action", "Adventure", "Crime"), "tv show"),
            new Movie("Martin", Arrays.asList("Comedy", "Drama", "Romance"), "tv show"),
            new Movie("The Ed Sullivan Show", Arrays.asList("Music", "Talk-Show"), "tv show"),
            new Movie("The Odd Couple", Arrays.asList("Comedy"), "tv show"),
            new Movie("Star Trek: The Next Generation", Arrays.asList("Action", "Adventure", "Sci-Fi"), "tv show"),
            new Movie("Beverly Hills, 90210", Arrays.asList("Drama", "Romance"), "tv show"),
            new Movie("The Walking Dead", Arrays.asList("Drama", "Horror", "Thriller"), "tv show"),
            new Movie("The Arsenio Hall Show", Arrays.asList("Comedy", "Family", "Music"), "tv show"),
            new Movie("ABC's Wide World of Sports", Arrays.asList("Sport"), "tv show"),
            new Movie("NFL Monday Night Football", Arrays.asList("Sport"), "tv show"),
            new Movie("Dallas", Arrays.asList("Drama", "Romance"), "tv show"),
            new Movie("Dynasty", Arrays.asList("Drama", "Romance"), "tv show"),
            new Movie("Buffy the Vampire Slayer", Arrays.asList("Action", "Drama", "Fantasy"), "tv show"),
            new Movie("The Vampire Diaries", Arrays.asList("Drama", "Fantasy", "Horror", "Romance"), "tv show"),
            new Movie("South Park", Arrays.asList("Animation", "Comedy"), "tv show"),
            new Movie("That's So Raven", Arrays.asList("Comedy", "Family", "Fantasy"), "tv show"),
            new Movie("Friday Night Lights", Arrays.asList("Drama", "Sport"), "tv show"),
            new Movie("Ugly Betty", Arrays.asList("Comedy", "Drama", "Romance"), "tv show"),
            new Movie("Desperate Housewives", Arrays.asList("Comedy", "Drama", "Mystery"), "tv show"),
            new Movie("Three's Company", Arrays.asList("Comedy"), "tv show"),
            new Movie("The Little Rascals", Arrays.asList("Comedy", "Family"), "tv show"),
            new Movie("The Boondocks", Arrays.asList("Animation", "Action", "Comedy"), "tv show"),
            new Movie("Everybody Hates Chris", Arrays.asList("Comedy", "Drama", "Music"), "tv show"),
            new Movie("New York Undercover", Arrays.asList("Crime", "Drama", "Thriller"), "tv show"),
            new Movie("Sanford and Son", Arrays.asList("Comedy"), "tv show"),
            new Movie("The Real World", Arrays.asList("Drama", "Reality-TV"), "tv show"),
            new Movie("L.A. Law", Arrays.asList("Drama"), "tv show"),
            new Movie("Law & Order", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("The Shield", Arrays.asList("Crime", "Drama", "Thriller"), "tv show"),
            new Movie("The Twilight Zone", Arrays.asList("Drama", "Fantasy", "Horror"), "tv show"),
            new Movie("Alfred Hitchcock Presents", Arrays.asList("Drama"), "tv show"),
            new Movie("The Simpsons", Arrays.asList("Animation", "Comedy"), "tv show"),
            new Movie("Family Guy", Arrays.asList("Animation", "Comedy"), "tv show"),
            new Movie("Family Ties", Arrays.asList("Comedy", "Drama", "Family"), "tv show"),
            new Movie("The Big Bang Theory", Arrays.asList("Comedy", "Romance"), "tv show"),
            new Movie("30 Rock", Arrays.asList("Comedy"), "tv show"),
            new Movie("Heroes", Arrays.asList("Drama", "Fantasy", "Sci-Fi"), "tv show"),
            new Movie("Grey's Anatomy", Arrays.asList("Drama", "Romance"), "tv show"),
            new Movie("Nip/Tuck", Arrays.asList("Drama"), "tv show"),
            new Movie("CSI: Crime Scene Investigation", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("The Honeymooners", Arrays.asList("Comedy", "Family"), "tv show"),
            new Movie("The Flintstones", Arrays.asList("Animation", "Adventure", "Comedy"), "tv show"),
            new Movie("Fat Albert and the Cosby Kids", Arrays.asList("Animation", "Comedy", "Family"), "tv show"),
            new Movie("The Fresh Prince of Bel-Air", Arrays.asList("Comedy"), "tv show"),
            new Movie("The Office", Arrays.asList("Comedy"), "tv show"),
            new Movie("A Different World", Arrays.asList("Comedy"), "tv show"),
            new Movie("American Idol", Arrays.asList("Music", "Reality-TV"), "tv show"),
            new Movie("Freaks and Geeks", Arrays.asList("Comedy", "Drama"), "tv show"),
            new Movie("Yo! MTV Raps", Arrays.asList("Music"), "tv show"),
            new Movie("NYPD Blue", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("In Living Color", Arrays.asList("Comedy", "Music"), "tv show"),
            new Movie("Chappelle's Show", Arrays.asList("Comedy", "Music"), "tv show"),
            new Movie("Breaking Bad", Arrays.asList("Crime", "Drama", "Thriller"), "tv show"),
            new Movie("The Wire", Arrays.asList("Crime", "Drama", "Thriller"), "tv show"),
            new Movie("I Love Lucy", Arrays.asList("Comedy", "Family"), "tv show"),
            new Movie("Seinfeld", Arrays.asList("Comedy"), "tv show"),
            new Movie("The West Wing", Arrays.asList("Drama"), "tv show"),
            new Movie("The Oprah Winfrey Show", Arrays.asList("News", "Talk-Show"), "tv show"),
            new Movie("The Cosby Show", Arrays.asList("Comedy", "Family", "Romance"), "tv show"),
            new Movie("The Sopranos", Arrays.asList("Crime", "Drama"), "tv show"),
            new Movie("The Tonight Show Starring Johnny Carson", Arrays.asList("Comedy", "Talk-Show"), "tv show"),
            new Movie("60 Minutes", Arrays.asList("Documentary", "News"), "tv show"),
            new Movie("Dexter", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("Entourage", Arrays.asList("Comedy", "Drama"), "tv show"),
            new Movie("Star Trek", Arrays.asList("Action", "Adventure", "Sci-Fi"), "tv show"),
            new Movie("M*A*S*H", Arrays.asList("Comedy", "Drama", "War"), "tv show"),
            new Movie("Lost", Arrays.asList("Adventure", "Drama", "Fantasy"), "tv show"),
            new Movie("Boston Public", Arrays.asList("Comedy", "Drama"), "tv show"),
            new Movie("The Practice", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("ER", Arrays.asList("Drama", "Romance"), "tv show"),
            new Movie("All in the Family", Arrays.asList("Comedy", "Drama"), "tv show"),
            new Movie("Curb Your Enthusiasm", Arrays.asList("Comedy"), "tv show"),
            new Movie("Saturday Night Live", Arrays.asList("Comedy", "Music"), "tv show"),
            new Movie("The Mary Tyler Moore Show", Arrays.asList("Comedy"), "tv show"),
            new Movie("Hill Street Blues", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("Good Times", Arrays.asList("Comedy"), "tv show"),
            new Movie("Sesame Street", Arrays.asList("Adventure", "Comedy", "Family"), "tv show"),
            new Movie("Bonanza", Arrays.asList("Western"), "tv show"),
            new Movie("The Carol Burnett Show", Arrays.asList("Comedy", "Family"), "tv show"),
            new Movie("Cheers", Arrays.asList("Comedy", "Drama"), "tv show"),
            new Movie("The Golden Girls", Arrays.asList("Comedy", "Drama"), "tv show"),
            new Movie("Murder, She Wrote", Arrays.asList("Crime", "Drama", "Mystery"), "tv show"),
            new Movie("Maude", Arrays.asList("Comedy"), "tv show"),
            new Movie("Boston Legal", Arrays.asList("Comedy", "Crime", "Drama"), "tv show"),
            new Movie("The Jeffersons", Arrays.asList("Comedy"), "tv show"),
            new Movie("House", Arrays.asList("Drama", "Mystery"), "tv show"),
            new Movie("Friends", Arrays.asList("Comedy", "Romance"), "tv show"),
            new Movie("Mad Men", Arrays.asList("Drama"), "tv show"),
            new Movie("Two and a Half Men", Arrays.asList("Comedy", "Romance"), "tv show"),
            new Movie("How I Met Your Mother", Arrays.asList("Comedy", "Drama", "Romance"), "tv show"),
            new Movie("Miami Vice", Arrays.asList("Action", "Crime", "Drama"), "tv show")
        );
    }

    
}
