-- Insert sample movies into the 'movie' table
INSERT INTO movie (title, genres) VALUES ('Toy Story', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('A Bug''s Life', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Toy Story 2', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Monsters, Inc.', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Finding Nemo', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('The Incredibles', 'Animation, Action, Adventure');
INSERT INTO movie (title, genres) VALUES ('Cars', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Ratatouille', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('WALL-E', 'Animation, Adventure, Sci-Fi');
INSERT INTO movie (title, genres) VALUES ('Up', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Toy Story 3', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Cars 2', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Brave', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Monsters University', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Inside Out', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('The Good Dinosaur', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Finding Dory', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Cars 3', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Coco', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Incredibles 2', 'Animation, Action, Adventure');
INSERT INTO movie (title, genres) VALUES ('Toy Story 4', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Onward', 'Animation, Adventure, Comedy');
INSERT INTO movie (title, genres) VALUES ('Soul', 'Animation, Adventure, Comedy');
